# Generated by Django 4.2.7 on 2023-12-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.IntegerField()),
                ('applicant', models.CharField(max_length=255)),
                ('facility_type', models.CharField(blank=True, max_length=255, null=True)),
                ('cnn', models.CharField(blank=True, max_length=255, null=True)),
                ('location_description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('block_lot', models.CharField(blank=True, max_length=255, null=True)),
                ('block', models.CharField(blank=True, max_length=255, null=True)),
                ('lot', models.CharField(blank=True, max_length=255, null=True)),
                ('permit', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('food_items', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('schedule', models.CharField(blank=True, max_length=255, null=True)),
                ('days_hours', models.CharField(blank=True, max_length=255, null=True)),
                ('noi_sent', models.CharField(blank=True, max_length=255, null=True)),
                ('approved', models.DateField(blank=True, null=True)),
                ('received', models.CharField(blank=True, max_length=255, null=True)),
                ('prior_permit', models.CharField(blank=True, max_length=255, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('fire_prevention_districts', models.IntegerField(blank=True, null=True)),
                ('police_districts', models.IntegerField(blank=True, null=True)),
                ('supervisor_districts', models.IntegerField(blank=True, null=True)),
                ('zip_codes', models.CharField(blank=True, max_length=255, null=True)),
                ('neighborhoods_old', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
